/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainForm;

import Connection.konek;
import javax.swing.ImageIcon;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import sun.util.calendar.LocalGregorianCalendar.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ahmad Maulana (201643500312).
 */
public class FormUser extends javax.swing.JFrame {
    
    //Connection conn;
    JasperReport JasReport;
    JasperPrint JasPrint;
    Map param = new HashMap();
    JasperDesign JasDes;

    /**
     * Creates new form FormUser
     */
    public FormUser() {
        initComponents();
        ImageIcon ico = new ImageIcon("src/Images/logom2.png");
        setIconImage(ico.getImage());
        this.setLocationRelativeTo(null);
        Locale locale = new Locale ("id","ID");
        Locale.setDefault(locale);
        new Thread(){
            public void run(){
                while(true){
                Calendar kal = new GregorianCalendar();
                int tahun = kal.get(Calendar.YEAR);
                int bulan = kal.get(Calendar.MONTH)+1;
                int hari = kal.get(Calendar.DAY_OF_MONTH);
                int jam = kal.get(Calendar.HOUR_OF_DAY);
                int menit = kal.get(Calendar.MINUTE);
                int detik = kal.get(Calendar.SECOND);
                String tanggal = hari + "-"+bulan+"-"+tahun;
                String waktu1 = jam + ":"+menit+":"+detik;
                String waktu2 = jam + ":"+menit+":"+detik;
                jLabel2.setText(tanggal);
                jLabel3.setText(waktu1);
                }
            }
        }.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_karyawan = new javax.swing.JMenu();
        data_karyawan = new javax.swing.JMenuItem();
        data_stkbrg = new javax.swing.JMenu();
        data_perangkat = new javax.swing.JMenuItem();
        menu_pemasok = new javax.swing.JMenu();
        data_pemasok = new javax.swing.JMenuItem();
        menu_distribusi = new javax.swing.JMenu();
        data_distribusi = new javax.swing.JMenuItem();
        menu_rpt = new javax.swing.JMenu();
        rpt_brg = new javax.swing.JMenuItem();
        rpt_karyawan = new javax.swing.JMenuItem();
        rpt_dtpemasok = new javax.swing.JMenuItem();
        rpt_dtdistribusi = new javax.swing.JMenuItem();
        menu_logout = new javax.swing.JMenu();

        jMenuItem6.setText("jMenuItem6");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard User");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 830));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("TANGGAL");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setText("JAM");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logom2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(433, 433, 433)
                .addComponent(jLabel1)
                .addContainerGap(443, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(255, 255, 255)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        menu_karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/identification_documents_20px.png"))); // NOI18N
        menu_karyawan.setText("Data Karyawan");
        menu_karyawan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        data_karyawan.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        data_karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/identification_documents_20px.png"))); // NOI18N
        data_karyawan.setText("Data Karyawan");
        data_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_karyawanActionPerformed(evt);
            }
        });
        menu_karyawan.add(data_karyawan);

        jMenuBar1.add(menu_karyawan);

        data_stkbrg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/laptop_20px.png"))); // NOI18N
        data_stkbrg.setText("Data Barang");
        data_stkbrg.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        data_perangkat.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        data_perangkat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/laptop_20px.png"))); // NOI18N
        data_perangkat.setText("Data Perangkat IT");
        data_perangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_perangkatActionPerformed(evt);
            }
        });
        data_stkbrg.add(data_perangkat);

        jMenuBar1.add(data_stkbrg);

        menu_pemasok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/procurement_20px.png"))); // NOI18N
        menu_pemasok.setText("Data Pemasok");
        menu_pemasok.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        data_pemasok.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        data_pemasok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/procurement_20px.png"))); // NOI18N
        data_pemasok.setText("Data Pemasok");
        data_pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_pemasokActionPerformed(evt);
            }
        });
        menu_pemasok.add(data_pemasok);

        jMenuBar1.add(menu_pemasok);

        menu_distribusi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exchange_20px.png"))); // NOI18N
        menu_distribusi.setText("Data Distribusi");
        menu_distribusi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        data_distribusi.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        data_distribusi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/workstation_20px.png"))); // NOI18N
        data_distribusi.setText("Data Distribusi Perangkat");
        data_distribusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_distribusiActionPerformed(evt);
            }
        });
        menu_distribusi.add(data_distribusi);

        jMenuBar1.add(menu_distribusi);

        menu_rpt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/graph_report_20px.png"))); // NOI18N
        menu_rpt.setText("Report");
        menu_rpt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        rpt_brg.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        rpt_brg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report_card_20px.png"))); // NOI18N
        rpt_brg.setText("Report Data Perangkat IT");
        rpt_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpt_brgActionPerformed(evt);
            }
        });
        menu_rpt.add(rpt_brg);

        rpt_karyawan.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        rpt_karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/administrator_male_20px.png"))); // NOI18N
        rpt_karyawan.setText("Report Data Karyawan");
        rpt_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpt_karyawanActionPerformed(evt);
            }
        });
        menu_rpt.add(rpt_karyawan);

        rpt_dtpemasok.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        rpt_dtpemasok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/supplier_20px.png"))); // NOI18N
        rpt_dtpemasok.setText("Report Data Pemasok");
        rpt_dtpemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpt_dtpemasokActionPerformed(evt);
            }
        });
        menu_rpt.add(rpt_dtpemasok);

        rpt_dtdistribusi.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        rpt_dtdistribusi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/download_pie_chart_report_20px.png"))); // NOI18N
        rpt_dtdistribusi.setText("Report Data Distribusi");
        rpt_dtdistribusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpt_dtdistribusiActionPerformed(evt);
            }
        });
        menu_rpt.add(rpt_dtdistribusi);

        jMenuBar1.add(menu_rpt);

        menu_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit_20px.png"))); // NOI18N
        menu_logout.setText("Logout");
        menu_logout.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        menu_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void data_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_karyawanActionPerformed
        // TODO add your handling code here:
        DataKaryawanUser dku = new DataKaryawanUser();
        dku.show();
        this.dispose();
    }//GEN-LAST:event_data_karyawanActionPerformed

    private void menu_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_logoutMouseClicked
        // TODO add your handling code here:
        FormLogin fl = new FormLogin();
        fl.show();
        this.dispose();
    }//GEN-LAST:event_menu_logoutMouseClicked

    private void data_perangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_perangkatActionPerformed
        // TODO add your handling code here:
        DataPerangkatUser dpu = new DataPerangkatUser();
        dpu.show();
        this.dispose();
    }//GEN-LAST:event_data_perangkatActionPerformed

    private void data_pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_pemasokActionPerformed
        // TODO add your handling code here:
        
        DataPemasokUser dpu = new DataPemasokUser();
        dpu.show();
        this.dispose();
    }//GEN-LAST:event_data_pemasokActionPerformed

    private void data_distribusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_distribusiActionPerformed
        // TODO add your handling code here:
        
        DataDistribusiUser ddu = new DataDistribusiUser();
        ddu.show();
        this.dispose();
    }//GEN-LAST:event_data_distribusiActionPerformed

    private void rpt_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpt_brgActionPerformed
        // TODO add your handling code here:
        try {
            //File file = new File("src/Laporan/LapBarang.jrxml");
            InputStream file = getClass().getResourceAsStream("/Laporan/LapBarang.jrxml");
            JasDes = JRXmlLoader.load(file);
            param.clear();
            JasReport = JasperCompileManager.compileReport(JasDes);
            JasPrint = JasperFillManager.fillReport(JasReport, param, konek.koneksiDb());
            JasperViewer.viewReport(JasPrint, false);
        } catch (Exception e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_rpt_brgActionPerformed

    private void rpt_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpt_karyawanActionPerformed
        // TODO add your handling code here:
        try {
            //File file = new File("src/Laporan/LapKaryawan.jrxml");
            InputStream file = getClass().getResourceAsStream("/Laporan/LapKaryawan.jrxml");
            JasDes = JRXmlLoader.load(file);
            param.clear();
            JasReport = JasperCompileManager.compileReport(JasDes);
            JasPrint = JasperFillManager.fillReport(JasReport, param, konek.koneksiDb());
            JasperViewer.viewReport(JasPrint, false);
        } catch (Exception e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_rpt_karyawanActionPerformed

    private void rpt_dtpemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpt_dtpemasokActionPerformed
        // TODO add your handling code here:
        try {
            //File file = new File("src/Laporan/LapPemasok.jrxml");
            InputStream file = getClass().getResourceAsStream("/Laporan/LapPemasok.jrxml");
            JasDes = JRXmlLoader.load(file);
            param.clear();
            JasReport = JasperCompileManager.compileReport(JasDes);
            JasPrint = JasperFillManager.fillReport(JasReport, param, konek.koneksiDb());
            JasperViewer.viewReport(JasPrint, false);
        } catch (Exception e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_rpt_dtpemasokActionPerformed

    private void rpt_dtdistribusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpt_dtdistribusiActionPerformed
        // TODO add your handling code here:
        try {
            //File file = new File("src/Laporan/LapPemasok.jrxml");
            InputStream file = getClass().getResourceAsStream("/Laporan/LapDistribusi.jrxml");
            JasDes = JRXmlLoader.load(file);
            param.clear();
            JasReport = JasperCompileManager.compileReport(JasDes);
            JasPrint = JasperFillManager.fillReport(JasReport, param, konek.koneksiDb());
            JasperViewer.viewReport(JasPrint, false);
        } catch (Exception e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_rpt_dtdistribusiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem data_distribusi;
    private javax.swing.JMenuItem data_karyawan;
    private javax.swing.JMenuItem data_pemasok;
    private javax.swing.JMenuItem data_perangkat;
    private javax.swing.JMenu data_stkbrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu menu_distribusi;
    private javax.swing.JMenu menu_karyawan;
    private javax.swing.JMenu menu_logout;
    private javax.swing.JMenu menu_pemasok;
    private javax.swing.JMenu menu_rpt;
    private javax.swing.JMenuItem rpt_brg;
    private javax.swing.JMenuItem rpt_dtdistribusi;
    private javax.swing.JMenuItem rpt_dtpemasok;
    private javax.swing.JMenuItem rpt_karyawan;
    // End of variables declaration//GEN-END:variables
}
