/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainForm;

import javax.swing.ImageIcon;

/**
 *
 * @author Ahmad Maulana (201643500312)
 */
public class LoadingScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoadingScreen
     */
    public LoadingScreen() {
        initComponents();
        ImageIcon ico = new ImageIcon("src/Images/logom2.png");
        setIconImage(ico.getImage());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Copyright = new javax.swing.JLabel();
        angka = new javax.swing.JLabel();
        Version = new javax.swing.JLabel();
        proses = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loading Screen");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Copyright.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        Copyright.setText("Copyright (C) 2020");
        getContentPane().add(Copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 103, -1));

        angka.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        angka.setText("99%");
        getContentPane().add(angka, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        Version.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        Version.setText("Versi 1.1");
        getContentPane().add(Version, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, 10));

        proses.setBackground(new java.awt.Color(0, 153, 255));
        proses.setForeground(new java.awt.Color(0, 102, 204));
        proses.setBorderPainted(false);
        proses.setFocusable(false);
        getContentPane().add(proses, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 480, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logom2.png"))); // NOI18N
        jPanel1.add(Logo);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 250));

        setSize(new java.awt.Dimension(502, 253));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadingScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Copyright;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Version;
    public javax.swing.JLabel angka;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JProgressBar proses;
    // End of variables declaration//GEN-END:variables
}
